title: Begrippenkaders | Netbeheer Nederland
remote_theme: just-the-docs/just-the-docs

defaults:
  - scope:
      path: ""
    values:
      layout: default

color_scheme: nbnl
logo: "/assets/images/logo.svg"
fav_icon: "/assets/images/favicon.png"
