title: Begrippenkader Energiesysteembeheer | Netbeheer Nederland
theme: just-the-docs
baseurl: /energiesysteembeheer

defaults:
  - scope:
      path: ""
    values:
      layout: default

color_scheme: nbnl
logo: "/assets/images/logo.svg"
fav_icon: "/assets/images/favicon.png"
